steps:

  # Install dependenies and run tests
  - name: "python:3.7-slim"
    id: Test
    entrypoint: 'bash'
    args: ['./scripts/install-app-dependencies.sh', '&&', './scripts/test-app.sh']

  # Docker build
  - name: "gcr.io/cloud-builders/docker"
    id: Build
    entrypoint: 'bash'
    args: ['./scripts/build-docker-image.sh']
    env:
      - 'PROJECT_ID=${PROJECT_ID}'
      - 'LOCATION=${LOCATION}'
      - 'SHORT_SHA=${SHORT_SHA}'

  # Docker push to Artifact Registry
  - name: "gcr.io/cloud-builders/gcloud"
    id: Push
    entrypoint: 'bash'
    args: ['./scripts/check-artifact-registry-repo-or-create-one.sh', '&&', '.scripts/push-image.sh']
    env:
      - 'PROJECT_ID=${PROJECT_ID}'
      - 'LOCATION=${LOCATION}'
      - 'SHORT_SHA=${SHORT_SHA}'

  # Access the id_github file from Secret Manager, and setup SSH
  - name: 'gcr.io/cloud-builders/git'
    id: Read Secret Manager
    secretEnv: ['SSH_KEY']
    entrypoint: 'bash'
    args:
    - -c
    - |
      echo "$$SSH_KEY" >> /root/.ssh/id_rsa
      chmod 400 /root/.ssh/id_rsa
      ssh-keyscan -t rsa github.com > known_hosts.github
      mv known_hosts.github /root/.ssh/known_hosts
    volumes:
    - name: 'ssh'
      path: /root/.ssh

  # Clones the env repo
  - name: "gcr.io/cloud-builders/git"
    id: Clone env repo
    entrypoint: 'bash'
    args: ['./scripts/clone-env-repo.sh']
    volumes:
    - name: 'ssh'
      path: /root/.ssh

  # This step generates the new manifest
  - name: 'gcr.io/cloud-builders/gcloud'
    id: Generate manifest
    entrypoint: 'bash'
    args: ['./scripts/generate-new-manifest.sh']
    env:
      - 'PROJECT_ID=${PROJECT_ID}'
      - 'LOCATION=${LOCATION}'
      - 'SHORT_SHA=${SHORT_SHA}'

  # This step pushes the manifest back to hello-cloudbuild-env
  - name: 'gcr.io/cloud-builders/gcloud'
    id: Push manifest
    entrypoint: 'bash'
    args: ['./scripts/pushes-manifest-back-to-env-repo.sh']
    env:
      - 'PROJECT_ID=${PROJECT_ID}'
      - 'LOCATION=${LOCATION}'
      - 'SHORT_SHA=${SHORT_SHA}'

images:
- '${LOCATION}-docker.pkg.dev/${PROJECT_ID}/my-repository/hello-cloudbuild:${SHORT_SHA}'

availableSecrets:
  secretManager:
  - versionName: projects/${PROJECT_ID}/secrets/cloudbuild-github-secret-key/versions/latest
    env: 'SSH_KEY'
