steps:

  # Install dependenies and run tests
  - name: "python:3.7-slim"
    id: Test
    entrypoint: 'bash'
    args: ['./scripts/install-app-dependencies.sh', '&&', './scripts/test-app.sh']

  # Docker build
  - name: "gcr.io/cloud-builders/docker"
    id: Build
    entrypoint: 'bash'
    args: ['./scripts/build-docker-image.sh']
    env:
      - 'PROJECT_ID=${PROJECT_ID}'
      - 'LOCATION=${LOCATION}'
      - 'SHORT_SHA=${SHORT_SHA}'

  # Docker push to Artifact Registry
  - name: "gcr.io/cloud-builders/gcloud"
    id: Push
    entrypoint: 'bash'
    args: ['./scripts/check-artifact-registry-repo-or-create-one.sh', '&&', '.scripts/push-image.sh']
    env:
      - 'PROJECT_ID=${PROJECT_ID}'
      - 'LOCATION=${LOCATION}'
      - 'SHORT_SHA=${SHORT_SHA}'

  # Clones the env repo
  - name: "gcr.io/cloud-builders/gcloud"
    id: Clone env repo
    entrypoint: 'bash'
    args: ['./scripts/clone-env-repo.sh']


images:
- '${LOCATION}-docker.pkg.dev/${PROJECT_ID}/my-repository/hello-cloudbuild:${SHORT_SHA}'
